#!/bin/bash

Convert(){
	num=0
	value=$1
	if [ -n "$1" ];then
	    if test $1 -gt 1023;then
	        while (($num<3))
	        do
                let value=value/1024
                #echo "$value"
                if test $value -lt 1024;then
            	    break 
                else
            	    let num++
                fi
            done
            case $num in
            0)
                unit="KB";;
            1)
                unit="MB";;
            *)
                unit="GB";;
            esac
            echo "$value $unit"
        else
    	    echo "$1 B"
        fi
    fi
}

export Convert

Convert $*